/**
 * The boundary between the booking core and the payment provider.
 *
 * ## Why this file exists in P2 with no implementation behind it
 *
 * P3 (`apps/paygate`, a separate branch) owns the provider and everything that
 * talks to it. The booking core still needs to know the SHAPE of that
 * conversation now, because two of its decisions depend on it — the hold TTL
 * has to outlive a charge attempt, and INV-4 requires that a payment can
 * succeed for a hold that has already expired. Writing the interface here and
 * nothing else keeps those decisions honest without either branch guessing at
 * the other's types.
 *
 * ## The two properties this interface is designed around
 *
 * **INV-3 — charged at most once.** `idempotencyKey` is not optional and is not
 * generated by the provider client. The caller mints it and persists it on the
 * `payments` row BEFORE the first attempt, so a retry — from the client, from a
 * timeout, or from a different replica — reuses the same key and the provider
 * cannot create a second charge. A key generated inside this call would be a
 * new key on every retry, which is the same as having none.
 *
 * **The response may lose the race with its own webhook.** `charge()` resolves
 * with `ChargeAccepted`, not with a terminal outcome, because the provider is
 * asynchronous and deliberately unreliable: the webhook announcing success can
 * arrive before the HTTP response that names the charge. That is why
 * `payments.charge_id` is nullable in the schema. Any interface that returned
 * "succeeded" or "failed" from this call would be modelling a provider that
 * does not exist, and the code written against it would be wrong in exactly the
 * cases the assessment tests.
 *
 * Nothing here is implemented in this phase. The hold and checkout paths do not
 * call it.
 */

export interface ChargeRequest {
  /** Minted and persisted by the caller before the first attempt. Never regenerated. */
  idempotencyKey: string;
  bookingId: string;
  amountMinor: bigint;
  currency: string;
  /** Propagated so one booking is traceable through the provider and back. */
  correlationId: string;
}

/**
 * The provider has ACCEPTED the charge, not completed it. The terminal outcome
 * arrives by webhook, possibly before this response does.
 */
export interface ChargeAccepted {
  chargeId: string;
  status: 'ACCEPTED';
}

export interface RefundRequest {
  idempotencyKey: string;
  chargeId: string;
  amountMinor: bigint;
  reason: string;
  correlationId: string;
}

export interface RefundAccepted {
  refundId: string;
  status: 'ACCEPTED';
}

export interface PaymentProvider {
  charge(request: ChargeRequest): Promise<ChargeAccepted>;
  refund(request: RefundRequest): Promise<RefundAccepted>;
}

/** Injection token. P3 binds the real Paygate client to it. */
export const PAYMENT_PROVIDER = Symbol('PAYMENT_PROVIDER');

/**
 * A provider that refuses to do anything, bound in P2 so the container is
 * complete and any accidental call fails loudly rather than silently
 * no-opping. Replaced in P3.
 */
export class UnimplementedPaymentProvider implements PaymentProvider {
  charge(): Promise<ChargeAccepted> {
    return Promise.reject(
      new Error('Payment provider is not wired up until P3 (feat/p3-payments-paygate)'),
    );
  }

  refund(): Promise<RefundAccepted> {
    return Promise.reject(
      new Error('Payment provider is not wired up until P3 (feat/p3-payments-paygate)'),
    );
  }
}
